english_final_training:
  language: en
  train_data_path: /Users/taaalwi1/Documents/ner/datasets/train_test/en.train
  validation_data_path:
  test_data_path: /Users/taaalwi1/Documents/ner/datasets/train_test/en.testb
  feature_template: baseline
  method: SVM
  model_name: SVM_final
  best_param:
    epsilon: 7.196856730011514e-06
    cost: 0.016378937069540647
  train_with_step: False

german_final_training:
  language: de
  train_data_path: /Users/taaalwi1/Documents/ner/datasets/train_test/de.train
  validation_data_path:
  test_data_path: /Users/taaalwi1/Documents/ner/datasets/train_test/de.testb
  feature_template: baseline
  method: SVM
  model_name: SVM_final
  best_param:
    epsilon: 7.196856730011514e-06
    cost: 0.016378937069540647
  train_with_step: False


french_final_training:
  language: en
  train_data_path: /Users/taaalwi1/Documents/ner/datasets/conll/nerc-conll2003/eng.train
  validation_data_path:
  test_data_path: /Users/taaalwi1/Documents/ner/datasets/conll/nerc-conll2003/eng.testa
  feature_template: baseline
  method: SVM
  model_name: SVM_final
  best_param:
    epsilon: 7.196856730011514e-06
    cost: 0.016378937069540647
  train_with_step: False

italian_final_training:
  language: en
  train_data_path: /Users/taaalwi1/Documents/ner/datasets/conll/nerc-conll2003/eng.train
  validation_data_path:
  test_data_path: /Users/taaalwi1/Documents/ner/datasets/conll/nerc-conll2003/eng.testa
  feature_template: baseline
  method: SVM
  model_name: SVM_final
  best_param:
    epsilon: 7.196856730011514e-06
    cost: 0.016378937069540647
  train_with_step: False

test_final_training:
  language: en
  train_data_path: /Users/taaalwi1/Documents/ner/datasets/conll/nerc-conll2003/eng-simplified.train
  validation_data_path:
  test_data_path: /Users/taaalwi1/Documents/ner/datasets/conll/nerc-conll2003/eng-simplified.testa
  feature_template: baseline
  method: SVM
  model_name: SVM_final
  best_param:
    epsilon: 7.196856730011514e-06
    cost: 0.016378937069540647
  train_with_step: False

parameter_selection:
  language: de
  train_data_path: /Users/taaalwi1/Documents/Swisscom/named_entity_recognition/data/training_data/de
  validation_data_path: None
  test_data_path: /Users/taaalwi1/Documents/Swisscom/named_entity_recognition/data/external_api_test/de_simplified.testb
  feature_template: baseline
  method: SVM
  model_name: SCV_parameter_selection
  number_of_trial: 2










